# Generated by Django 5.1.1 on 2024-10-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('realisateur', 'Realisateur'), ('utilisateur', 'Utilisateur')], max_length=12, null=True),
        ),
    ]
