# Generated by Django 5.1.1 on 2025-03-13 16:31
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(
                blank=True, null=True, upload_to='media/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('realisateur', 'Realisateur'), (
                'utilisateur', 'Utilisateur')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
