# Generated by Django 5.1.1 on 2025-04-15 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_proposed', to='sondage.question'),
        ),
    ]
