# Generated by Django 5.1.1 on 2025-04-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0002_alter_proposed_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
