# Generated by Django 5.1.1 on 2024-10-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0002_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='critique',
            name='description',
            field=models.CharField(default='la description de la critique', max_length=250),
            preserve_default=False,
        ),
    ]
