# Generated by Django 5.1.1 on 2024-10-11 23:50
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=20)),
                ('out_date', models.DateField()),
                ('casting', models.CharField(max_length=250)),
                ('duree', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/film')),
            ],
        ),
    ]
