# Generated by Django 5.1.1 on 2024-10-17 21:08
from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_film_uid_alter_film_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='accept_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='publie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='media/film'),
        ),
    ]
