# Generated by Django 5.1.1 on 2024-10-20 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2024, 10, 20, 18, 2, 36, 647632, tzinfo=datetime.timezone.utc))),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('creator', 'creator'), ('participant', 'participant')], default='participant', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
