name: Pipeline_ci_cd_movie
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Test package flake8
        run: |
          flake8 . --exit-zero

  Test:
    runs-on: ubuntu-latest
    needs: check_syntaxe

    services:
      db:
        image: postgres:15.8
        ports:
          - 5432:5432
        env:  # Correction ici
          POSTGRES_USER: movi_user
          POSTGRES_PASSWORD: movi_pass
          POSTGRES_DB: tasmovie_dev

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov=conf --cov-report=term-missing

  Build:
    runs-on: ubuntu-latest
    needs: [Test]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        env:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation des secrets Docker
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilisation des secrets Docker
        run: |
          docker login -u $username -p $password

      - name: Docker build image
        run: |
          docker build . -t dounoh0/movie:latest

      - name: Push image to Docker Hub
        run: |
          docker push dounoh0/movie:latest
